version: "3.8"

services:
  yourls:
    image: yourls
    restart: always
    environment:
      - YOURLS_DB_HOST=${YOURLS_DB_HOST}
      - YOURLS_DB_PASS=${YOURLS_DB_PASS}
      - YOURLS_DB_USER=${YOURLS_DB_USER}
      - YOURLS_DB_NAME=${YOURLS_DB_NAME:-yourls}
      - YOURLS_PASS=${YOURLS_PASS}
      - YOURLS_USER=${YOURLS_USER}
      - YOURLS_SITE=${YOURLS_SITE}
    depends_on:
      - yourls-db
    links:
      - yourls-db
    ports:
      - 8080:80

  yourls-db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE:-yourls}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - yourls-data:/var/lib/mysql

volumes:
  yourls-data:
